### ISSUE TITLE
TensorRT "Ran out of input"?

### ISSUE THREAD

**Issue by Selur** [HolyWu/vs-realesrgan#18]
Using:
```
# Imports
import vapoursynth as vs
# getting Vapoursynth core
core = vs.core
import site
import os
# Adding torch dependencies to PATH
path = site.getsitepackages()[0]+'/torch_dependencies/'
path = path.replace('\\', '/')
os.environ["PATH"] = path + os.pathsep + os.environ["PATH"]
# Loading Plugins
core.std.LoadPlugin(path="i:/Hybrid/64bit/vsfilters/Support/fmtconv.dll")
core.std.LoadPlugin(path="i:/Hybrid/64bit/vsfilters/SourceFilter/LSmashSource/vslsmashsource.dll")
# source: 'G:\TestClips&Co\files\test.avi'
# current color space: YUV420P8, bit depth: 8, resolution: 640x352, fps: 25, color matrix: 470bg, yuv luminance scale: limited, scanorder: progressive
# Loading G:\TestClips&Co\files\test.avi using LWLibavSource
clip = core.lsmas.LWLibavSource(source="G:/TestClips&Co/files/test.avi", format="YUV420P8", stream_index=0, cache=0, prefer_hw=0)
# Setting color matrix to 470bg.
clip = core.std.SetFrameProps(clip, _Matrix=5)
clip = clip if not core.text.FrameProps(clip,'_Transfer') else core.std.SetFrameProps(clip, _Transfer=5)
clip = clip if not core.text.FrameProps(clip,'_Primaries') else core.std.SetFrameProps(clip, _Primaries=5)
# Setting color range to TV (limited) range.
clip = core.std.SetFrameProp(clip=clip, prop="_ColorRange", intval=1)
# making sure frame rate is set to 25
clip = core.std.AssumeFPS(clip=clip, fpsnum=25, fpsden=1)
clip = core.std.SetFrameProp(clip=clip, prop="_FieldBased", intval=0)
original = clip
from vsrealesrgan import RealESRGAN
# adjusting color space from YUV420P8 to RGBH for VsRealESRGAN
clip = core.resize.Bicubic(clip=clip, format=vs.RGBH, matrix_in_s="470bg", range_s="limited")
# resizing using RealESRGAN
clip = RealESRGAN(clip=clip, device_index=0, trt=True, trt_cache_path="G:/Temp", num_streams=4) # 2560x1408
# resizing 2560x1408 to 640x352
# adjusting resizing
clip = core.resize.Bicubic(clip=clip, format=vs.RGBS, range_s="limited")
clip = core.fmtc.resample(clip=clip, w=640, h=352, kernel="lanczos", interlaced=False, interlacedd=False)
original = core.resize.Bicubic(clip=original, width=640, height=352)
# adjusting output color from: RGBS to YUV420P8 for x264Model
clip = core.resize.Bicubic(clip=clip, format=vs.YUV420P8, matrix_s="470bg", range_s="limited", dither_type="error_diffusion")
original = core.text.Text(clip=original,text="Original",scale=1,alignment=7)
clip = core.text.Text(clip=clip,text="Filtered",scale=1,alignment=7)
stacked = core.std.StackHorizontal([original,clip])
# Output
stacked.set_output()
```
I get

Failed to evaluate the script:
Python exception: Ran out of input
```
Traceback (most recent call last):
File "src\cython\vapoursynth.pyx", line 2866, in vapoursynth._vpy_evaluate
File "src\cython\vapoursynth.pyx", line 2867, in vapoursynth._vpy_evaluate
File "C:\Users\Selur\Desktop\test_2.vpy", line 32, in 
clip = RealESRGAN(clip=clip, device_index=0, trt=True, trt_cache_path="G:/Temp", num_streams=4) # 2560x1408
File "I:\Hybrid\64bit\Vapoursynth\Lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
return func(*args, **kwargs)
File "I:\Hybrid\64bit\Vapoursynth\Lib\site-packages\vsrealesrgan\__init__.py", line 284, in RealESRGAN
module = [torch.load(trt_engine_path) for _ in range(num_streams)]
File "I:\Hybrid\64bit\Vapoursynth\Lib\site-packages\vsrealesrgan\__init__.py", line 284, in 
module = [torch.load(trt_engine_path) for _ in range(num_streams)]
File "I:\Hybrid\64bit\Vapoursynth\Lib\site-packages\torch\serialization.py", line 795, in load
return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
File "I:\Hybrid\64bit\Vapoursynth\Lib\site-packages\torch\serialization.py", line 1002, in _legacy_load
magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input
```
Works fine with trt=False.

->Any idea what is going wrong there?

**Comment by Selur** [comment]
`clip = RealESRGAN(clip=clip, device_index=0, trt=True, num_streams=4) # 2560x1408`
also works, so it's probably related to the specification of the trt_cache_path.
I wanted the cache files to be put into "G:/Temp". 

Clearing all the cache files I got:
```
2022-12-17 17:33:20.973 I:\Hybrid\64bit\Vapoursynth\Lib\site-packages\torch_tensorrt\fx\tracer\acc_tracer\acc_tracer.py:584: UserWarning: acc_tracer does not support currently support models for training. Calling eval on model before tracing.warnings.warn( I:\Hybrid\64bit\Vapoursynth\Lib\site-packages\torch_tensorrt\fx\tracer\acc_tracer\acc_tracer.py:584: UserWarning: acc_tracer does not support currently support models for training. Calling eval on model before tracing.warnings.warn( == Log pass before/after graph to C:\Users\Selur\AppData\Local\Temp\tmpg1hrpgex, before/after are the same = True == Log pass before/after graph to C:\Users\Selur\AppData\Local\Temp\tmpg1hrpgex, before/after are the same = True == Log pass before/after graph to C:\Users\Selur\AppData\Local\Temp\tmpfih9jle3, before/after are the same = True == Log pass before/after graph to C:\Users\Selur\AppData\Local\Temp\tmpfih9jle3, before/after are the same = True Now lowering submodule _run_on_acc_0 Now lowering submodule _run_on_acc_0 split_name=_run_on_acc_0, input_specs=[InputTensorSpec(shape=torch.Size([1, 3, 352, 640]), dtype=torch.float16, device=device(type='cuda', index=0), shape_ranges=[], has_batch_dim=True)] split_name=_run_on_acc_0, input_specs=[InputTensorSpec(shape=torch.Size([1, 3, 352, 640]), dtype=torch.float16, device=device(type='cuda', index=0), shape_ranges=[], has_batch_dim=True)] Timing cache is used! Timing cache is used! TRT INetwork construction elapsed time: 0:00:00.100656 TRT INetwork construction elapsed time: 0:00:00.100656
--
2022-12-17 17:34:26.129 Build TRT engine elapsed time: 0:01:02.929279 Build TRT engine elapsed time: 0:01:02.929279 Lowering submodule _run_on_acc_0 elapsed time 0:01:04.851174 Lowering submodule _run_on_acc_0 elapsed time 0:01:04.851174 Now lowering submodule _run_on_acc_2 Now lowering submodule _run_on_acc_2 split_name=_run_on_acc_2, input_specs=[InputTensorSpec(shape=torch.Size([1, 3, 1408, 2560]), dtype=torch.float16, device=device(type='cuda', index=0), shape_ranges=[], has_batch_dim=True), InputTensorSpec(shape=torch.Size([1, 3, 1408, 2560]), dtype=torch.float16, device=device(type='cuda', index=0), shape_ranges=[], has_batch_dim=True)] split_name=_run_on_acc_2, input_specs=[InputTensorSpec(shape=torch.Size([1, 3, 1408, 2560]), dtype=torch.float16, device=device(type='cuda', index=0), shape_ranges=[], has_batch_dim=True), InputTensorSpec(shape=torch.Size([1, 3, 1408, 2560]), dtype=torch.float16, device=device(type='cuda', index=0), shape_ranges=[], has_batch_dim=True)] Timing cache is used! Timing cache is used! TRT INetwork construction elapsed time: 0:00:00 TRT INetwork construction elapsed time: 0:00:00 Build TRT engine elapsed time: 0:00:00.450448 Build TRT engine elapsed time: 0:00:00.450448 Lowering submodule _run_on_acc_2 elapsed time 0:00:00.485813 Lowering submodule _run_on_acc_2 elapsed time 0:00:00.485813
2022-12-17 17:34:26.937 Failed to evaluate the script:Python exception: Parent directory G: does not exist.Traceback (most recent call last):File "src\cython\vapoursynth.pyx", line 2866, in vapoursynth._vpy_evaluateFile "src\cython\vapoursynth.pyx", line 2867, in vapoursynth._vpy_evaluateFile "G:\Temp\tempPreviewVapoursynthFile17_33_17_871.vpy", line 32, in clip = RealESRGAN(clip=clip, device_index=0, trt=True, trt_cache_path="G:/Temp", num_streams=4) # 2560x1408File "I:\Hybrid\64bit\Vapoursynth\Lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_contextreturn func(*args, **kwargs)File "I:\Hybrid\64bit\Vapoursynth\Lib\site-packages\vsrealesrgan\__init__.py", line 280, in RealESRGANtorch.save(module, trt_engine_path)File "I:\Hybrid\64bit\Vapoursynth\Lib\site-packages\torch\serialization.py", line 422, in savewith _open_zipfile_writer(f) as opened_zipfile:File "I:\Hybrid\64bit\Vapoursynth\Lib\site-packages\torch\serialization.py", line 309, in _open_zipfile_writerreturn container(name_or_buffer)File "I:\Hybrid\64bit\Vapoursynth\Lib\site-packages\torch\serialization.py", line 287, in __init__super(_open_zipfile_writer_file, self).__init__(torch._C.PyTorchFileWriter(str(name)))RuntimeError: Parent directory G: does not exist.
```
And empty file "g:/Temp/realesr-animevideov3.pth_NVIDIA GeForce RTX 4080_trt-8.5.1.7_640x352_fp16_workspace-1073741824.pt" was created.

**Comment by HolyWu** [comment]
Weirdly, you have to use backslash r"G:\Temp" instead of slash "G:/Temp" for it to work.

**Comment by Selur** [comment]
Ah, okay.
That works (and is really strange)!
Thanks!
